; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	https://github.com/Terrapin-Rocket-Team/Astra-Rocket.git#airbrake
	https://github.com/odriverobotics/ODriveArduino.git
	Astra@0.2.1+sha.3f6b486
build_flags = 
	-D ENV_TEENSY

[env:native]
platform = native
lib_deps = 
	https://github.com/Terrapin-Rocket-Team/Astra-Rocket.git#airbrake
	https://github.com/odriverobotics/ODriveArduino.git
	throwtheswitch/Unity@^2.6.0
	https://github.com/Terrapin-Rocket-Team/Astra-Support.git#main
	Astra@0.2.1+sha.3f6b486
lib_ignore = SdFat
lib_compat_mode = off
test_build_src = yes
build_flags = 
	-Wno-unknown-pragmas
	-std=c++17
	-DARDUINO=100
	-DNATIVE=1
	-DNATIVE_NO_STDOUT_DATA=1
	-DNOLOGI=1
	-DUNITY_INCLUDE_DOUBLE
	-lws2_32
	-fpermissive
build_src_filter = 
	+<*>
test_framework = unity
lib_ldf_mode = chain+
debug_build_flags = -g -O0 -fstack-protector-all
